newrelic/nri-docker

CHANGELOG.md, Dockerfile, Makefile, docker-definition.yml, src/docker.go
- Renamed the integration executable from nr-docker to nri-docker in order to be consistent with the package naming. **Important Note:** if you have any security module rules (eg. SELinux), alerts or automation that depends on the name of this binary, these will have to be updated.
=> Update executable prefix from nr- to nri-.

docker-definition.yml
This avoids breaking the release of the agent before docker is bundled with it
=> Added back docker-definition

docker-config.yml.sample
Otherwise, containerized agent release fails and, in consequence,
integrations release (due to installation check failures)
=> Temporarily put back docker-config sample file

src/nri/sampler.go
Harmless but redundant operation.
=> Remove duplicated cpou sampling

docker-config.yml
Next agent version will require:
- Setting the `feature` inside a `when` field
- Using the `file_exists` property to avoid running the integration when docker is not running
=> Updating conditional execution to next Agent version

CHANGELOG.md, src/biz/metrics_test.go, src/docker.go, src/nri/sampler.go, src/raw/cgroup.go, src/raw/cgroup_test.go, src/raw/metrics.go, src/raw/util.go, src/raw/util_test.go
This pr will add detection of cgroup location:
1. --cgroup_path command line argument
2. checking existence of cgroup usual paths:
"/sys/fs/cgroup",
"/cgroup",
3. parsing mounts file
=> Detect cgroup path

CHANGELOG.md, src/biz/metrics.go, src/biz/metrics_test.go, src/nri/metrics.go, src/nri/sampler.go
Added metric `memoryUsageLimitPercent` that reports the usage of the container memory as
a percentage of the limit. If there is no limit defined, this metric is not reported.
Metric `memorySizeLimitBytes` is not reported anymore when there is no such limit
(before it was reported as `0`)
=> [IHOST-2496] Added memoryUsageLimitPercent and changed memorySizeLimitBytes

CHANGELOG.md, src/nri/sampler.go
The logic in this conditional was broken for Fargate containers, as the check on `container.Status != "running"` was removed.
I took some time to simplify the `if`, as it was very difficult to read. The logic to identify containers that are not running is:
* their **state** isn't `running` (case insensitive, covers classic cgroups containers)
* their **status** isn't `running` (case insensitive, covers ECS containers)
* their **status** doesn't start with `up` (case insensitive, covers cgroups container with the systemd driver)
There's no need to check if `state` or `status` are or not empty.
=> Fix and simplify the condition to skip non-running containers

CHANGELOG.md, src/nri/sampler.go, src/raw/aws/fargate_inspector.go, src/raw/aws/fargate_inspector_test.go, src/raw/aws/fargate_metadata.go
Fixes #49 
When running in transparent mode, as is the case in Fargate, the agent will not decorate metrics with Fargate metadata such as `awsRegion`, `ecsLaunchType`, and `ecsClusterName`. Breaking queries that use such attributes.
In this PR we fix this by pulling such metadata from the docker container labels that Fargate adds to the container information, by parsing the task arn and the cluster name. This is the same way in which https://github.com/newrelic/nri-ecs obtains this information. `RegionFromTask` and `ResourceNameAndARNBase` have been pulled from said repo as well.
[json-comparison.tar.gz](https://github.com/newrelic/nri-docker/files/5517495/json-comparison.tar.gz)
=> Embed fargate data in container samples

CHANGELOG.md, src/biz/metrics.go, src/biz/metrics_aws_test.go, src/biz/metrics_test.go, src/docker.go, src/nri/sampler.go, src/nri/sampler_test.go
The Docker daemon might keep exited containers indefinitely if they're not properly removed by whoever started them: either by running such containers with `--rm`, by removing the container manually after its execution or by running `docker container prune`. 
To avoid spamming New Relic with this data this PR changes the behavior of this integration to avoid reporting containers that are exited for more than 24 hours ago. This value is configurable through the `ExitedContainersTTL` argument.
If some users want to keep the old behavior, they can set it to `0`.
=> Add feature to stop reporting exited containers after a certain TTL

build/.goreleaser.yml, build/nix/fix_archives.sh
During the pipeline migration the config file added to the bundle was not the expected by the agent to be automatically activated. This Pr fixes that.
=> fix: add correct config to the bundle

src/biz/metrics_aws_test.go, src/biz/testdata/v4_task_container_stats_response.json, src/biz/testdata/v4_task_metadata_response.json, src/docker.go, src/raw/aws/fargate_fetcher.go, src/raw/aws/fargate_metadata.go, src/raw/aws/fargate_raw_metrics.go, src/raw/network.go
Adding support for[ Task metadata endpoint v4](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html)
```
The task metadata endpoint version 4 functions like the version 3 endpoint,
but provides additional network metadata for your containers and tasks. 
Additional network metrics are available when querying the /stats endpoints as well.
```
=> feat(fargate): adding networking info

build/release.mk
- Install goversioninfo instead of go get to not add to go.mod
=> Do not add goversioninfo to the mod file

src/config/config.go, src/docker.go, src/raw/cgroup.go, src/raw/cgroup_detect.go, src/raw/cgroup_detect_test.go, tests/integration/cgroups_fetcher_mock_test.go, tests/integration/metrics_test.go
Although the removed has been _marked as deprecated_ long ago and the removed configuration arguments don't appear either in documentation or in examples, those are two configuration parameters being removed. Therefore, any user relying on them could be affected.
=> refactor: [BREAKING CHANGE] stop supporting cgroupspath and cgroupsdriver configuration

.github/workflows/e2e.yml, .github/workflows/push_pr.yml
Closes https://github.com/newrelic/nri-docker/issues/122.
Add CI job to run integration tests on ubuntu 22.04, supporting cgroups v2. However, there are apparently some issues as reflected in this issue comments https://github.com/actions/virtual-environments/issues/5490#issuecomment-1118319996 so we allow the job to fail.
=> Add ci job to run integration tests on ubuntu 22.04

.github/workflows/e2e.yml, test/e2e/e2e_spec.yml
These are the four excluded metrics that aren't available:
- `docker.container.memorySizeLimitBytes`
- `docker.container.memoryUsageLimitPercent`
- `docker.container.memorySwapLimitBytes`
- `docker.container.memorySwapLimitUsagePercent`
All of them are directly consumed from the [containerd library](https://github.com/containerd/cgroups/blob/188f73d13086fdfc4a26bdda70f0362203552e3a/v2/manager.go#L452), related to memory limits. IMHO it makes sense as the resource limitations has changed from cgroups v1 and v2, including the resource limitation feature on a container basis in v2.
=> Add ci job to run e2e tests for cgroups v2

src/raw/aws/fargate_fetcher.go
We have a ticket for a nil pointer dereference:
```
[WARN] computing Storage Driver stats: only devicemapper is supported
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x240 pc=0x7f5640]
goroutine 1 [running]:
github.com/newrelic/nri-docker/src/raw/aws.(*FargateFetcher).getFargateContainerMetrics(0xc4202ae880, 0xc42000e430, 0xc42028d480, 0x832901)
/go/src/github.com/newrelic/nri-docker/src/raw/aws/fargate_fetcher.go:112 +0x4b0
github.com/newrelic/nri-docker/src/raw/aws.(*FargateFetcher).fargateStatsFromCacheOrNew(0xc4202ae880, 0xc42000e430, 0x0, 0x0)
/go/src/github.com/newrelic/nri-docker/src/raw/aws/fargate_fetcher.go:76 +0x20a
github.com/newrelic/nri-docker/src/raw/aws.(*FargateFetcher).Fetch(0xc4202ae880, …
```
=> Log a Warning in case there is a `nil` from Fargate

go.mod, go.sum
=> chore(dependencies): update dependencies to fix vulnerabilities

.github/workflows/security.yml, CHANGELOG.md, go.mod, go.sum
This pr:
- adds trivy failing in the first commit due to the security vulnerability
- fixes the security vulnerability
=> chore(dependencies): updated dependencies

CHANGELOG.md, src/nri/sampler.go, src/nri/sampler_test.go
Depending on the source some of the attributes are not being populated, for instance in Fargate the `state` is not present on the metadata API. 
Currently the integration is sending this attributes with an empty value, this PR removes these attributes when the values is an empty string.
Note:
I studied the possibility to add this into the[ integration SDK](https://github.com/newrelic/infra-integrations-sdk/blob/v3.7.3/data/metric/metrics.go#L91) but since that func is returning an error it would be a breaking change, and also there might be a use case where empty values would make sense to be sent.
=> Remove attributes with empty values (NR-107455)

Dockerfile, build/Dockerfile
We decided to pin golang version and [automerge them](https://github.com/newrelic/coreint-automation/commit/398ade41391d36da64320e123d832566d201601b)
=> chore(golang): ping golang version

.github/workflows/e2e.yml, .github/workflows/on_prerelease.yml, .github/workflows/push_pr.yml, .github/workflows/repolinter.yml, .github/workflows/security.yml
I misread the PRs from renovate and merged PRs that changed the tag to a commit hash.
We don't know if renovate will update commits written like that and if renovate might stick to master instead of following tag conventions.
As this is an untested territory I prefer to revert the change and keep working with tags.
=> Revert actions using hash instead of tag

CHANGELOG.md, src/biz/metrics.go, src/config/config.go, src/docker.go, src/nri/sampler.go, test/integration/metrics_cgroupsv2_test.go
A customer states that is not able to see some CPU metrics if the interval is set to more than 1 minute.
These CPU Metrics that are failing rely on the storer to be able to calculate the delta/rate and the storer has hardcoded the value to 1 minute.
This PR allows the storer TTL to be variable for customers who might need it.
=> Allow to set the cache TTL of storer (NR-179361)

.github/renovate.json5, .github/workflows/e2e.yaml, .github/workflows/on_prerelease.yaml, .github/workflows/on_push_pr.yaml
- Changes renovate config to skip bumping the runners used for cgroup v1 testing
- Adds reusable workflows
=> chore: use reusable workflows

.github/renovate.json5
the package name is actually `ubuntu`
the idea is to avoid this bump https://github.com/newrelic/nri-docker/pull/198
=> fix renovate config

src/docker.go, src/raw/client.go, src/raw/dockerapi/fetcher.go, test/integration/dockerapi_fetcher_test.go
This PR introduces a new fetcher to get the metrics through the docker API. The fetcher is not used yet.
* The main function has been split to make it more readable and easier to extend.
* A new `DockerStatsClient` interface has been defined.
* A new package `raw.dockerapi` has been introduced, container the new fetcher scaffolding.
* A new temporal integration tests has been included: it shows how to build the new fetcher and how to fetch stats metrics from docker API. It can be used to quickly get docker container inspect and stats data in order to continue implementing the new fetcher.
* The new fetcher is not ready to be used (it includes some _unimplemented_ methods which would panic). However, since it is not used, the PR can be merged safely.
* Most metrics should come from `docker …
=> NR-221180: docker api fetcher scaffolding

test/integration/common.go, test/integration/dockerapi_fetcher_test.go
Extend the integration tests of the docker-api fetcher to include CPU, Memory and Blkio metrics.
=> extend docker-api integration test

src/biz/metrics.go, src/nri/sampler.go, test/integration/metrics_test.go
Exited container metrics fetch was causing the follow error:
```log
error fetching metrics for container <container_id>: failed to parse cgroups2 paths, error: failed to open file: /proc/0/cgroup, while detecting cgroup paths error: open /proc/0/cgroup: no such file or directory
```
Since metrics still were tried to be collected from an exited container where Pid changes from the original value to `0`, which does not represent a real Pid but a condition of that container (exited state).
Changes:
- Metrics fetch is no longer executed for exited containers, expired or not.
- Parsing error related to time since exited are only returned in case `TTL != 0`
Note: 
The process function is a bit confusing since return values doesn't follow a clear standar of (value,error) . I didn't want to …
=> fix: exited container fetch metrics cause error

src/biz/metrics.go, src/biz/metrics_aws_test.go, src/nri/sampler.go, test/integration/common.go, test/integration/metrics_cgroupsv2_test.go, test/integration/metrics_test.go, test/integration/mocks.go
This PR updates the logic to only report blkio metrics that are explicitly set, defaulting to nil for any metrics that are not.
=> NR-231647: report only set blkio metrics, default to nil

test/e2e/e2e_spec.yml
`docker-compose` v1 is EOL, and we need to move to `docker compose` (wit a space).
=> [NR-286408] chore: update docker compose command

CHANGELOG.md, src/raw/cgroupv2.go, test/integration/metrics_cgroupsv2_test.go, test/integration/metrics_test.go, test/integration/mocks.go
`SoftLimitBytes` metric values was being fetched from `low` value in `memory.events` instead of `memory.low` (check [cgroups-v2 specs](https://git.kernel.org/pub/scm/linux/kernel/git/tj/cgroup.git/tree/Documentation/admin-guide/cgroup-v2.rst) for details).
Since the corresponding value is in the response of `docker inspect` (which is called in a previous step), this PR updates the cgroups-v2 fetcher to get it from there.
=> [NR-231640] fix: fetch SofLimitBytes from docker inspect

CHANGELOG.md, src/raw/cgroupv2.go, test/integration/metrics_cgroupsv2_test.go, test/integration/metrics_test.go
The integration is currently reporting `cpu.weight` from cgroups-v2 as the value for `CPUShares` metric. This is a bit misleading because, even if the meaning of `cpu.weight` according to the [cgroups-v2 spec](https://git.kernel.org/pub/scm/linux/kernel/git/tj/cgroup.git/tree/Documentation/admin-guide/cgroup-v2.rst#:~:text=nr_bursts%0A%09%2D%20burst_usec-,cpu.weight,-A%20read%2Dwrite) is the same as `cpu-shares` in [docker's runtime options](https://docs.docker.com/engine/containers/resource_constraints/#cpu), the scale is different.
**cpu.weigh**:
>	A read-write single value file which exists on non-root
>	cgroups.  The default is "100".
>
>	For non idle groups (cpu.idle = 0), the weight is in the
>	range [1, 10000].
>
>	If the cgroup has been configured to be SCHED_IDLE (cpu.idle = 1), …
=> [NR-231645] fix: fetch cpuShares from docker inspect

.github/workflows/on_prerelease.yaml, build/.goreleaser.yml, build/Dockerfile, build/release.mk, build/s3-publish-schema.yml, src/fips.go
* update goreleaser version
* add fips compliant package building
* update renovate config to update go version in Dockerfile builds
[test s3 package for prerelease](http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/rohan-fips-test/)
`goreleaser` output with local testing:
```log
root@b6b613dee1a0:/app# bin/goreleaser release --config ./build/.goreleaser.yml --clean
• cleaning distribution directory
• loading environment variables
• getting and validating git state
• git state                                      commit=cb94086849408cb78901684dd57b1556f34339b3 branch=NR-287144-build-fips-compliant-packages current_tag=v2.1.0 previous_tag=v2.0.9 dirty=false
⨯ release failed after 0s                          error=git tag v2.1.0 was not made against commit …
```
=> add fips compliant package builds

build/.goreleaser.yml, build/s3-publish-schema.yml
To be consistent with other OHIs package names for `apt` and `zypper`, updating package names for `nri-docker`.
=> Fix fips pkg names

src/config/config.go, src/docker.go, src/raw/cgroup.go, src/raw/cgroup_detect.go, src/raw/cgroup_test.go, src/raw/cgroupv1.go, src/raw/cgroupv1_detect.go, src/raw/cgroupv1_detect_test.go, src/raw/cgroupv2.go, src/raw/cgroupv2_detect.go, src/raw/cgroupv2_detect_test.go, src/raw/system_cpu_reader.go, src/raw/system_cpu_reader_test.go, src/util/util.go, src/util/util_all.go, src/util/util_linux.go, test/integration/metrics_cgroupsv2_test.go, test/integration/metrics_test.go, test/integration/mocks.go
* This modifies the module to enable adding windows functionality. 
* Certain decisions made to minimise duplication.
* Cgoups will only be supported for linux. Windows and darwin will use dockerAPI.
=> feat(docker-win): add main for windows

src/constants/constants.go, src/raw/dockerapi/fetcher.go, src/raw/dockerapi/fetcher_test.go, src/util/util_all.go, src/util/util_linux.go, test/integration/dockerapi_fetcher_test.go, test/integration/metrics_test.go
There are no changes for Network metrics for windows. Therefore, just doing some housekeeping here. Adding platfrom to use for Memory and CPU metrics.
=> feat(windows): add platform as a member to decide os specific metrics

CHANGELOG.md, build/.goreleaser.yml, docker-config-win.yml
Removed `file_exists: /var/run/docker.sock` from the linux config for windows.
=> fix: use a separate config file for windows

CHANGELOG.md, src/biz/metrics.go, src/biz/metrics_all.go, src/biz/metrics_all_test.go, src/biz/metrics_windows.go, src/biz/metrics_windows_test.go, src/nri/sampler_windows.go
* feat(windows): add cpuCount metric
* feat(windows): use totalMemroy from config if available
With below command:
`docker run --rm --cpu-count=1 --memory=2GB -it mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd`
Resulting metrics:
```powershell
PS C:\Program Files\New Relic\newrelic-infra\newrelic-integrations\bin> .\nri-docker.exe --pretty --verbose
[WARN] computing Storage Driver stats: only devicemapper is supported
[DEBUG] Could not fetch metric value from docker API: the key "file" was not found in memory_stats.stats
[DEBUG] Could not fetch metric value from docker API: the key "anon" was not found in memory_stats.stats
[DEBUG] Could not fetch metric value from docker API: the key "kernel_stack" was not found in memory_stats.stats
[DEBUG] Could not fetch metric value from docker …
```
=> Nr 375198 update cpu memory metrics

.github/workflows/e2e.yaml, .github/workflows/on_push_pr.yaml
This pull request is driven by the upcoming deprecation of the Ubuntu 20.04 Actions runner image. GitHub has announced the following timeline for deprecation:
- **Deprecation Start Date**: 2025-02-01
- **Full Unsupported Date**: 2025-04-15
Given these dates, it is crucial to transition to supported runner images to ensure that our CI/CD pipelines do not encounter disruptions.
- **Objective**: Update all pipelines to use the `ubuntu-latest` runner image instead of the soon-to-be deprecated `ubuntu-20.xx`.
- **Background**: By updating to `ubuntu-latest`, we align our workflows with the latest stable and supported environment that GitHub provides. 
- **Impact**: Workflows using the `ubuntu-20.04` image label should be updated to `ubuntu-latest`.
=> NR-403516: Move all pipelines from ubuntu-20 runners to ubuntu-latest
