newrelic/nri-docker

- vendor/vendor.json
replaces https://github.com/newrelic/nri-docker/pull/5
> Fix SDK vendor

- Makefile
This integrations only can be built for Linux, so fixing the OS target would make it buildable from non Linux envs
> Target OS for make

- Makefile
Related to https://github.com/newrelic/nri-docker/pull/8
> Target OS for gocov

- Makefile
This fixes Jenkins packaging issue.
> It should be temporal as integrations are moving towards go modules.
> Fix Jenkins packaging

- docker-config.yml
> Rename config feature_flag to feature

- Makefile-package.mk
Correct release dependency at the time is 1.9.0
> Update agent dependency

- .travis.yml
- src/biz/metrics.go
- src/nri/sampler_test.go
- src/raw/aws/fargate_fetcher.go
- src/raw/aws/fargate_inspector.go
- src/raw/aws/fargate_metadata.go
- src/raw/cgroup_test.go
- src/raw/util_test.go
NR infrastructure integrations require Go v1.10
> Golang v1.10

- THIRD_PARTY_NOTICES.md
> feat(opensource): added THIRD_PARTY_NOTICES.md

- .github/workflows/prerelease.yml
- .github/workflows/push_pr.yml
- build/.goreleaser.yml
- build/Dockerfile
- build/ci.mk
- build/upload_artifacts_gh.sh
ci/migration gha multpile changes
> ci: migration gha multpile changes

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Updated links to the centralized CODE_OF_CONDUCT.md document
> remove local CODE_OF_CONDUCT.md 

- .github/workflows/e2e.yml
- test/e2e/agent_dir/docker-compose.yml
- test/e2e/agent_dir/newrelic-infra-agent/Dockerfile
- test/e2e/deps/Dockerfile
- test/e2e/docker-compose.yml
- test/e2e/docker.yml
- test/e2e/e2e_spec.yml
This PR adds E2E tests for docker with cgroups v1
> Adding E2E tests cgroups v1

- .github/workflows/on_prerelease.yml
- .github/workflows/on_release.yml
- .github/workflows/push_pr.yml
- .github/workflows/trigger_prerelease.yml
- .gitignore
- CHANGELOG.md
- Makefile
This PR adds Automatic Releases by leveraging the `release-toolkit` and [this](https://github.com/newrelic/newrelic-coreint-automation/blob/master/.github/workflows/trigger_prerelease.yaml) shared workflow.
> NR-101029: Add automatic releases

- .github/workflows/e2e.yml
- .github/workflows/push_pr.yml
- .github/workflows/security.yml
adding renovate branches to actually test before automerge
> test on push to renovate branch

- CHANGELOG.md
Held releases temporally, since #201 introduced a bug
> fix: held release

- CHANGELOG.md
- src/nri/sampler.go
- Adds sdk 3.8.2 
- TmpPath for container_cpu file is created with provided custom tmp folder or default.
> Adds sdk 3.8.2 AND TmpPath for container_cpu file is created with provided custom tmp folder or default.

- src/raw/dockerapi/fetcher.go
- src/raw/dockerapi/fetcher_test.go
- test/integration/dockerapi_fetcher_test.go
Adds network metrics.
To be addressed in a separate PR:
- integration test
> feat: Add network metrics

- src/raw/dockerapi/fetcher.go
- src/raw/dockerapi/fetcher_test.go
- test/integration/common.go
- test/integration/dockerapi_fetcher_test.go
Adds pid metrics, totally compatible with current implementation.
> feat: add pids metrics

- CHANGELOG.md
- src/biz/metrics.go
- src/nri/sampler.go
> fix: exited container fetch metrics cause error log

- go.mod
- go.sum
- src/raw/aws/arn.go
- src/raw/aws/fargate_inspector.go
- removes aws dep by copying a little bit of code
- bumps docker dep
> chore: remove aws dep

- src/biz/storage.go
- src/biz/storage_test.go
- src/docker.go
- src/nri/sampler.go
- src/nri/sampler_test.go
- src/raw/cgroup.go
- test/integration/mocks.go
- Fixes io metrics collection
- Add sampler tests
> fix: io metrics collection

- CHANGELOG.md
- go.sum
- src/nri/sampler.go
- src/raw/cgroup.go
Adds changelog and merge from master commits
> Prepare release

- .github/CODEOWNERS
> update codeowners to ohai

- .github/workflows/on_prerelease.yaml
- .github/workflows/on_push_pr.yaml
- build/.goreleaser.yml
- build/release.mk
- build/s3-publish-schema.yml
- build/windows/fix_archive.sh
- build/windows/fix_archives.sh
- build/windows/set_exe_properties.sh
- build/windows/unit_tests.ps1
- build/windows/versioninfo.json.template
- docker-win-definition.yml
- src/raw/network_stats_getter.go
- src/raw/network_stats_getter_test.go
- src/raw/util_test.go
* Add powershell script to run unit tests on windows
* Update goreleaser to build windows exe and zip. Also build archive for darwin.
* Update s3 upload schema to publish windows binaries
> feat(docker-win): build, release windows binary and archive

- src/nri/sampler.go
- src/nri/sampler_all.go
- src/nri/sampler_test.go
- src/nri/sampler_windows.go
https://docs.docker.com/reference/api/engine/version/v1.48/#tag/Container/operation/ContainerStats
> feat(win): remove pid related metrics for windows
